# Generated by Django 6.0.3 on 2026-03-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing')], max_length=32)),
                ('installed_capacity', models.FloatField()),
                ('installed_capacity_unit', models.CharField(default='MW', max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('technical_highlights', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'project_scopes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScopeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_memberships', to='projects.project')),
                ('project_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.projectscope')),
            ],
            options={
                'db_table': 'project_scope_memberships',
                'unique_together': {('project', 'project_scope')},
            },
        ),
        migrations.CreateModel(
            name='ProjectScopeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='projects/scopes')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project_scope_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectscopemembership')),
            ],
            options={
                'db_table': 'project_scope_images',
                'ordering': ['order'],
            },
        ),
    ]
