# Generated by Django 6.0.3 on 2026-04-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content_html', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='about_us/sections')),
            ],
            options={
                'db_table': 'about_page_sections',
            },
        ),
        migrations.CreateModel(
            name='CorePrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_key', models.CharField(max_length=64)),
                ('color_class', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_principles',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CorePrinciplesIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_html', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='about_us/core_principles')),
                ('image_caption_title', models.CharField(blank=True, max_length=255)),
                ('image_caption_subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'core_principles_intros',
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'team_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='about_us/team/photo')),
                ('profile_photo', models.FileField(blank=True, upload_to='about_us/team/profile_photo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_expertise', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about_us.teamcategory')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='about_us.teammember')),
            ],
            options={
                'db_table': 'team_member_categories',
                'ordering': ['order', 'technical_expertise'],
            },
        ),
    ]
