# Generated by Django 6.0.3 on 2026-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='bio',
            new_name='profile',
        ),
    ]
