# Generated by Django 6.0.3 on 2026-03-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_key', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('theme_color', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'expertise_categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, upload_to='services/sectors')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'service_sectors',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.expertisecategory')),
                ('project_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertise_items', to='projects.projectscope')),
            ],
            options={
                'db_table': 'expertise_items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
