# Generated by Django 6.0.3 on 2026-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
