# Generated by Django 6.0.5 on 2026-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsattachment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
