# Generated by Django 6.0.3 on 2026-04-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitiateSynergySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=255)),
                ('cta_note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'initiate_synergy_sections',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'job_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipRoadmapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'partnership_roadmap_sections',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Independent Consultant', 'Independent Consultant')], max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('is_open', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='contact_us.jobcategory')),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('year_completed', models.CharField(blank=True, max_length=16)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('abilities', models.TextField(blank=True)),
                ('software_proficiency', models.TextField(blank=True)),
                ('employment_status', models.CharField(blank=True, max_length=255)),
                ('experience_sector', models.CharField(blank=True, max_length=255)),
                ('years_experience', models.CharField(blank=True, max_length=32)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=64)),
                ('cv_file', models.FileField(blank=True, upload_to='contact_us/applications/cv')),
                ('cover_letter_file', models.FileField(blank=True, upload_to='contact_us/applications/cover')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contact_us.jobposting')),
            ],
            options={
                'db_table': 'job_applications',
            },
        ),
        migrations.CreateModel(
            name='PartnershipRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_key', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contact_us.partnershiproadmapsection')),
            ],
            options={
                'db_table': 'partnership_roadmap_steps',
                'ordering': ['order', 'milestone'],
            },
        ),
    ]
