# Generated by Django 6.0.3 on 2026-04-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitiateSynergySection',
        ),
        migrations.RemoveField(
            model_name='partnershiproadmapstep',
            name='section',
        ),
        migrations.DeleteModel(
            name='PartnershipRoadmapSection',
        ),
        migrations.DeleteModel(
            name='PartnershipRoadmapStep',
        ),
    ]
